name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: DIS_${{ github.run_number }}  # Define the artifact name here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Log artifact name
        run: echo "Artifact name is DIS_${{ github.run_number }}"

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: DIS_${{ github.run_number }}
          path: ./publish
          retention-days: 5

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Log artifact name
        run: echo "Using artifact name: DIS_${{ needs.build.outputs.artifact_name }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: DIS_${{ needs.build.outputs.artifact_name }}
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
