name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: gha-runner-scale-set-linux
    steps:
      [ ... ]
      - name: "Upload Artifact"
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: DIS_${{ env.VERSION }}
          path: ./publish
          retention-days: 5
  
  publish-docker-image:
    runs-on: gha-runner-scale-set-linux
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4 # UPDATE HERE
        with:
          name: DIS_${{ env.VERSION }}
      - name: List Artifact Contents
        run: ls -R


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
