name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to Node.js 18 for Next.js compatibility

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Export project to static HTML
        run: npm run export

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-site
          path: ./out  # Default export folder for static sites in Next.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-site
          path: ./out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Matches the download path above
